import * as utils from '../../support/utils.js'

describe('Given that the user accesses the login screen', () => {
  beforeEach('Visit Url', () => {
    cy.visit('/')
    cy.get('[data-test="login-button"]').click()
  })

  context('When the registered user fills in the fields with valid data', () => {
    it('Then you must log in to the system', () => {
      cy.login(Cypress.env('validEmail'),Cypress.env('validPassword'))
      })
    })
  
  context('When the user fills in the field incorrectly', () => {
    const messageErrorSymbol = 'Inclua um "@" no endereço de e-mail'
    const messageError = `Insira uma parte depois`

    it(`Then you should see the message “${messageErrorSymbol}” generated by the browser`, () => {
      utils.login('email', Cypress.env('validPassword'))
      cy.get('@emailField').then(($el) => {
        cy.wrap($el[0].validationMessage).should('contain',`${messageErrorSymbol}`)
      })
    })
    it(`Then you should see the message “${messageError}” generated by the browser`, () => {
      utils.login('email@', Cypress.env('validPassword'))
      cy.get('@emailField').then(($el) => {
        cy.wrap($el[0].validationMessage).should('contain',`${messageError}`)
      })
    })
  })
})

