const { validEmail, validPassword, invalidEmail, invalidPassword } = Cypress.env()

describe('Given that the user accesses the login screen', () => {
  beforeEach('Visit Url', () => {
    cy.visit('/')
    cy.get('[data-test="login-button"]').click()
  })

  context('When the registered user fills in the fields with valid data', () => {
    it('Then you must log in to the system', () => {
      cy.signIn(validEmail, validPassword)
      })
    })
  
  context('When the user fills in the field incorrectly', () => {
    it('Should fill in login fields incorrectly and display error messages to the user on the page', () => {
      cy.signIn(invalidEmail, invalidPassword)
      cy.get('[data-test="submit-button"]').click()
      cy.get('form').should('contain', 'Por favor, verifique o email digitado').and('contain','A senha deve conter pelo menos uma letra maiúscula, um número e ter entre 6 e 15 caracteres')
    })
    it('Then click the submit button without filling out the credentials ao clicar no botão de enviar sem preencher as credenciais', () => {
      cy.get('[data-test="submit-button"]').click()
      cy.get('form').should('contain','É necessário informar um endereço de email').and('contain', 'Insira sua senha')
    })
    it(`Then you should see the message "Please include an '@' in the email address." generated by the browser`, () => {
      cy.signIn(invalidEmail, validPassword)
      cy.get('@emailField').then(($el) => {
        cy.wrap($el[0].validationMessage).should('contain', "Please include an '@' in the email address.")
      })
    })
    it(`Then you should see the message "Please enter a part following '@'" generated by the browser`, () => {
      cy.signIn(invalidEmail+'@', validPassword)
      cy.get('@emailField').then(($el) => {
        cy.wrap($el[0].validationMessage).should('contain', "Please enter a part following '@'")
      })
    })
  })
})

