name: Cypress Tests

on:
  push:
    branches: main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Write the cypress.env.json file 
        run: |
          echo '${{ secrets.CYPRESS_ENV_FILE }}' > cypress.env.json

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          run: npm run cy:run
